# Generated by Django 3.1.2 on 2020-10-21 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='quizzes', serialize=False, to='api.course')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Quiz Name')),
            ],
            options={
                'verbose_name_plural': 'Quizzes',
            },
        ),
    ]
