# Generated by Django 3.1.2 on 2020-10-21 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201021_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_option', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='correct_answers', to='api.answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correct_answers', related_query_name='correct_answer', to='api.question')),
            ],
        ),
    ]
