export const TEACHER_LOADING = "TEACHER_LOADING";
export const TEACHER_LOADED = "TEACHER_LOADED";
export const TEACHER_AUTH_ERROR = "TEACHER_AUTH_ERROR";
export const TEACHER_LOGIN_SUCCESS = "TEACHER_LOGIN_SUCCESS";
export const TEACHER_LOGIN_FAIL = "TEACHER_LOGIN_FAIL";
export const TEACHER_LOGOUT_SUCCESS = "TEACHER_LOGOUT_SUCCESS";
export const TEACHER_REGISTER_SUCCESS = "TEACHER_REGISTER_SUCCESS";
export const TEACHER_REGISTER_FAIL = "TEACHER_REGISTER_FAIL";
